services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_spring
    environment:
      - MYSQL_DATABASE=practica2
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
volumes:
  db:
