services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_spring2
    environment:
      - MYSQL_DATABASE=practica3
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
